services:
  mysql:
    image: mariadb:10.11
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var_lib/mysql
    networks:
      - slurm-network

  slurmdbd:
    image: slurm-docker-cluster:${IMAGE_TAG}
    build: &build-config
      context: .
      args:
        SLURM_TAG: ${SLURM_TAG}
        GOSU_VERSION: ${GOSU_VERSION}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql
    networks:
      - slurm-network

  slurmctld:
    image: slurm-docker-cluster:${IMAGE_TAG}
    build: *build-config
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes: &slurm-volumes
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
      - ./cgroup.conf:/etc/slurm/cgroup.conf
      - scratch:/data/scratch
      - ${STORAGE_PATH}:/data/storage
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"
    networks:
      - slurm-network

  c1:
    image: slurm-docker-cluster:${IMAGE_TAG}
    build: *build-config
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    volumes: *slurm-volumes
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      - slurm-network

volumes:
  etc_munge:
  etc_slurm:
  var_lib_mysql:
  var_log_slurm:
  scratch:

networks:
  slurm-network:
    driver: bridge
