services:
  mysql:
    image: mariadb:10.11
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var_lib/mysql
    networks:
      - slurm-network

  slurmdbd:
    image: slurm-docker-cluster:${SLURM_VERSION}
    build:
      context: .
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql
    networks:
      - slurm-network

  slurmctld:
    image: slurm-docker-cluster:${SLURM_VERSION}
    build:
      context: .
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes: &slurm-volumes
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./cgroup.conf:/etc/slurm/cgroup.conf
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"
    networks:
      - slurm-network

  c:
    image: slurm-docker-cluster:${SLURM_VERSION}
    build:
      context: .
    command: ["slurmd"]
#    hostname: c1
#    container_name: c1
    volumes: *slurm-volumes
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      - slurm-network
    deploy:
      mode: replicated
      replicas: 16
      endpoint_mode: vip

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:

networks:
  slurm-network:
    driver: bridge
