services:
  mysql:
    image: mariadb:11.8
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var_lib/mysql
    networks:
      - slurm-network

  slurmdbd:
    image: slurm-docker-cluster:${IMAGE_TAG}
    build: &build-config
      context: .
      args:
        SLURM_TAG: ${SLURM_TAG}
        GOSU_VERSION: ${GOSU_VERSION}
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    configs:
      - source: slurm_conf
        target: /etc/slurm/slurm.conf
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    cap_add:
      - SYS_ADMIN
    expose:
      - "6819"
    depends_on:
      - "mysql"
    networks:
      - slurm-network

  slurmctld:
    image: slurm-docker-cluster:${IMAGE_TAG}
    build: *build-config
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    configs: &slurm_configs
      - source: cgroup_conf
        target: /etc/slurm/cgroup.conf
      - source: slurm_conf
        target: /etc/slurm/slurm.conf
    volumes: &slurm-volumes
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
      - scratch:/data/scratch
      - ${STORAGE_PATH}:/data/storage
    cap_add:
      - SYS_ADMIN
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"
    networks:
      - slurm-network

  node:
    image: slurm-docker-cluster:${IMAGE_TAG}
    build: *build-config
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["slurmd"]
    volumes: *slurm-volumes
    configs: *slurm_configs
    cap_add:
      - SYS_ADMIN
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      - slurm-network
    deploy:
      mode: replicated
      replicas: ${NNODES}

configs:
  cgroup_conf:
    file: ./etc/slurm/cgroup.conf
  slurm_conf:
    file: ./etc/slurm/slurm.conf

volumes:
  etc_munge:
  etc_slurm:
  var_lib_mysql:
  var_log_slurm:
  scratch:

networks:
  slurm-network:
    driver: bridge
