x-build-base: &build-base
  context: .
  args:
    SLURM_TAG: ${SLURM_TAG}
    GOSU_VERSION: ${GOSU_VERSION}

services:
  mysql:
    image: mariadb:11.8
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var_lib/mysql
    networks: [slurm-network]

  slurmdbd:
    image: slurm-docker-cluster:${IMAGE_TAG}
    build: *build-base
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    container_name: slurmdbd
    hostname: slurmdbd
    configs:
      - source: slurm_conf
        target: /etc/slurm/slurm.conf
    volumes:
      - ./entrypoint-slurmdbd.sh:/usr/local/bin/entrypoint.sh
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    privileged: false
    expose: ["6819"]
    depends_on: ["mysql"]
    networks: [slurm-network]

  slurmctld:
    image: slurm-docker-cluster:${IMAGE_TAG}
    build: *build-base
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    container_name: slurmctld
    hostname: slurmctld
    configs:
      - source: cgroup_conf
        target: /etc/slurm/cgroup.conf
      - source: slurm_conf
        target: /etc/slurm/slurm.conf
    volumes:
      - ./entrypoint-slurmctld.sh:/usr/local/bin/entrypoint.sh
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
      - scratch:/data/scratch
      - home_user:/home/user
      - ${STORAGE_PATH}:/data/storage
    privileged: true
    expose: ["6817"]
    depends_on: ["slurmdbd"]
    networks: [slurm-network]

  node:
    image: slurm-docker-cluster:${IMAGE_TAG}
    build: *build-base
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    volumes:
      - ./entrypoint-slurmd.sh:/usr/local/bin/entrypoint.sh
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
      - home_user:/home/user
      - scratch:/data/scratch
      - ${STORAGE_PATH}:/data/storage
    configs:
      - source: cgroup_conf
        target: /etc/slurm/cgroup.conf
      - source: slurm_conf
        target: /etc/slurm/slurm.conf
    privileged: true
    expose: ["6818"]
    depends_on: ["slurmctld"]
    networks: [slurm-network]
    deploy:
      mode: replicated
      replicas: ${NNODES}

configs:
  cgroup_conf:
    file: ./etc/slurm/cgroup.conf
  slurm_conf:
    file: ./etc/slurm/slurm.conf

volumes:
  etc_munge:
  etc_slurm:
  var_lib_mysql:
  var_log_slurm:
  home_user:
  scratch:

networks:
  slurm-network:
    driver: bridge
